name: Deploy
on:
  push:
    branches:
      - master

jobs:
  codecov:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Restore composer cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
      - run: composer install --no-interaction --no-ansi --optimize-autoloader --no-progress --prefer-dist
      - run: cat dev/mysql/*.sql > dev/mysql_dump.sql
      - run: sudo systemctl start mysql.service
      - run: mysql -uroot -proot  < dev/mysql_dump.sql
      - run: bin/phpunit -d memory_limit=512M --coverage-clover=build/coverage.xml
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/coverage.xml
          verbose: true
